### ISSUE TITLE
Language Option

### ISSUE THREAD

**Issue by derekstephen** [TTT-2/ttt2-totem#2]
Currently, some of the messages in chat don't have an option for English and I had to go through the code and modify the messages.

Is there any look towards adding English as an option to switch languages between?

Sorry I know this is something very small, and I know only one [file](https://github.com/TTT-2/ttt2-totem/blob/master/lua/totem/cl_init.lua) would need to be looked at.

**Comment by saibotk** [comment]
Sure this is a small fix, i can implement, i guess this was overlooked when implemented, usually everything is done using the Lang system. Thanks for reporting the issue 👍🏻

**Comment by saibotk** [comment]
Done
